[tool.poetry]
name = "my-project"
version = "0.1.0"
description = ""
authors = ["Max <mack.mair@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
